tools/picard_collectrawwgsmetrics.cwl, tools/picard_collectwgsmetrics.cwl
modified:   picard_collectrawwgsmetrics.cwl
modified:   picard_collectwgsmetrics.cwl
change these two QC step picard version to 2.15.0
version 2.8.3 do not have option USE_FAST_ALGORITHM
=> change picard version 2.8.3 to 2.15.0

tools/gatk_validategvcf.cwl, tools/picard_collectgvcfcallingmetrics.cwl
update `picard_collectgvcfcallingmetrics.cwl` and `gatk_validategvcf.cwl` to recognize proper dbsnp index file as the secondary input
=> :wrench: update/picard-dbsnp-index

tools/expression_checkcontamination.cwl, tools/gatk_haplotypecaller_35.cwl, workflows/cavatica/kfdrc_alignment_inputcram_cavatica.cwl, workflows/cavatica/kfdrc_alignment_pipeline_cavatica.cwl, workflows/cavatica/kfdrc_haplotypecaller_cavatica.cwl, workflows/cavatica/kfdrc_postbqsr_cavatica.cwl
- add tool with gatk3.5 for haplotypecaller. 
- update `expression_checkcontamination.cwl` to cover different `@RG SM` situation
- If BWA `SM` tag is not presented or presented at the last column in the header `@RG`, `VerifyBamID` will generate weird results which will cause problem for input for `gatk_haplotypecaller`. 
- update workflow relative path of tools
@zhangb1 @dmiller15 @kmhernan  please review, comment
=> :wrench: update/add gatk35 & update checkcontam

tools/gatk_haplotypecaller_cram.cwl, workflows/kf-cram2gvcf-custom.cwl
No difference between using local bam or cram, however piping into python script instead of using picard rename definitely saves time.
=> Gvcf temp bam test

tools/sambamba_merge_anylist.cwl
Encountered a bug when running a very small BAM through the new alignment pipeline. The merge step would fail because sambamba merge requires more than one BAM file for the tool to run. We do not view single bams as errors and want to have them continue on the pipeline. Therefore, we need to allow single bams to pass this step.
Resolves: https://github.com/d3b-center/bixu-tracker/issues/662
* Environment: cwltool 3.0.20200324120055, Cavatica
* Test files: See Cavatica run
=> 🔧 pass thru merge with only one bam

tools/python_createsequencegroups.cwl
Issue brought to our attention by the IPC folks where escape characters were not being properly resolved in cwltool. This PR addresses the issue by changing tabs and newlines to their ASCII codes (chr(9) for tab and chr(10) for newline). 
Resolves https://github.com/d3b-center/bixu-tracker/issues/659
* Environment: cwltool 3.0.20200324120055 and Cavatica
* Test files: Reference dict in cavatica test
=> 🔧 no escapes in arguments

subworkflows/kfdrc_process_bam.cwl, subworkflows/kfdrc_process_bamlist.cwl, subworkflows/kfdrc_process_pe_readslist2.cwl, subworkflows/kfdrc_process_pe_set.cwl, subworkflows/kfdrc_process_se_readslist2.cwl, subworkflows/kfdrc_process_se_set.cwl, subworkflows/kfdrc_rgbam_to_realnbam.cwl, tools/bwa_mem_naive.cwl, workflows/kfdrc_alignment_wf_cyoa.cwl
Per https://github.com/d3b-center/bixu-tracker/issues/681, this adds the -T flag with a zero value such that reads in = reads out. No filtering may occur.
Resolves: https://github.com/d3b-center/bixu-tracker/issues/681
Ticket changed specs to want OPS to be able to set this flag at the top level. Updated PR to make the value an input and carry that input through the various subworkflows out into the main workflow.
* Environment: cwltool 3.0.20200324120055
* Test files: See Cavatica tests
=> ✨ set T flag for bwa

tools/bundle_secondaryfiles.cwl, tools/bwa_mem_naive.cwl, tools/picard_gatherbamfiles.cwl, tools/sambamba_merge_anylist.cwl, tools/untar_indexed_reference.cwl, workflows/kfdrc_alignment_wf_cyoa.cwl
These are changes necessary to allow our alignment workflow to run end-to-end using cwltool:
- Pulled out the rg_string value from the argument block. When left in the argument block, cwltool would not "interpret" the value. So if you hand it ('hello\\tworld') it would explicitly pass the double escaped tab ('\\t') rather than simply a tab ('\t'). The solution was to split the argument block into things that come before and after it then use inputBinding to put it between them.
- No longer rm bams in gatherbamfiles. The bams it tries to delete are typically readonly files in cwltool and users won't have rm permissions.
- Rewrote the flatten function in sambamba merge anylist. The old function was only flattening a single level so I rewrote it to recursively flatten. All other changes are …
=> 🇪🇸 cwltool compatibility

subworkflows/kfdrc_rgbam_to_realnbam.cwl, tools/bamtofastq_chomp.cwl
Replaces #100 
This PR attempts to address the problems arising with our alignment workflow in Cavatica. While there's nothing wrong with the existing code it appears some functionality of cwl cannot be reliably implemented in Cavatica for the time being. In this case, it's the outputEval of the tool bamtofastq_chomp.cwl. To temporarily get around this while SBG determines the cause, I have modified the pipeline to use the old preparerg expressiontool. This pipeline should be usable while SBG investigates the cause.
* Environment: Cavatica, cwltool 3.0.20200324120055
* Test files: See Cavatica …
=> 🐛 rg exptool for cavatica bug

subworkflows/kfdrc_bam_to_gvcf.cwl, workflows/kfdrc-gatk-haplotypecaller-wf.cwl, workflows/kfdrc_alignment_wf.cwl
Changes:
- BAM to gVCF subworkflow tools updated to what is run in the CRAM to gVCF standalone
- Alignment input to generate_gvcf step updated to fulfill new requirements
- CRAM to gVCF now uses same generate_gvcf subworkflow as alignment
- Iterate release
- Cleaned up some trailing whitespaces
Closes https://github.com/d3b-center/bixu-tracker/issues/822
Checking the gvcf stats, old & new have identical stats indicating that nothing has been broken in the update.
* Environment: cwltool 3.0.20200807132242, Cavatica
* Test files: See Cavatica test
=> 🚲 hc wf and alignemnt use same subwf

docs/KFDRC_SENTIEON_ALIGNMENT_GATK_HAPLOTYPER_WORKFLOW_README.md, readme.md, subworkflows/kfdrc_process_bam.cwl, subworkflows/kfdrc_process_bamlist.cwl, subworkflows/kfdrc_rgbam_to_realnbam.cwl, subworkflows/rgbam_to_bwa_payload.cwl, tools/bamtofastq_chomp.cwl, tools/biobambam_bamtofastq.cwl, workflows/kfdrc_alignment_wf.cwl, workflows/kfdrc_sentieon_alignment_wf.cwl
This PR satisfies a request from the ops team to allow for our alignment workflows to accept cram input (with a bonus, but unlikely case of SAM too) for realignment. Biggest change is an optional input of cram_reference as, if the input cram was from a different reference, it needs the reference used to generate that file.
Closes # https://github.com/d3b-center/bixu-tracker/issues/1539
* Environment:
* Test files:
=> 🛠 Added input cram support

tools/picard_collectalignmentsummarymetrics_conditional.cwl, tools/picard_collectgcbiasmetrics_conditional.cwl, tools/sentieon_bqsr.cwl, tools/sentieon_run_agg_metrics.cwl, workflows/kfdrc_sentieon_alignment_wf.cwl
This PR modifies the naming of the outputs in the Sentieon alignment workflow to match those produced by the GATK-based alignment workflow. One caveat:
- Changed the name of the summary metrics file produced by Picard GC Bias metrics. The updated name more clearly defines what is in the file and matches the output produced by Sentieon.
- Changed the name of AlignmentSummary metrics output. We have had it as `alignmentsummary_metrics` which is probably a typo as it doesn't match what GATK puts in their docs: https://gatk.broadinstitute.org/hc/en-us/articles/5358857328667-AlignmentSummaryMetrics. The output is now ".alignment_summary_metrics". We will have to update the docs to reflect this.
Closes https://github.com/d3b-center/bixu-tracker/issues/1512
Please describe the tests that you ran …
=> 🚚  sync alignment wf output names

readme.md, subworkflows/kfdrc_process_bam.cwl, subworkflows/kfdrc_process_bamlist.cwl, subworkflows/kfdrc_rgbam_to_realnbam.cwl, tools/bamtofastq_chomp.cwl, workflows/kfdrc_alignment_wf.cwl
Opens the port for bamtofastq_chomp step. This port allows some troubleshooting for extremely large, multi-readgroup BAM inputs where aggressive job stacking caused instances to run out of disk space.
Fixes https://github.com/d3b-center/bixu-tracker/issues/1432
* Environment:
* Test files:
=> 🐛  bamtofastq cpu port open

tools/sentieon_ReadWriter.cwl, workflows/kfdrc_sentieon_alignment_wf.cwl
Sentieon readwriter will make a CRAM.BAI file whenever it is outputting a CRAM file. The reason for this is that:
```
Both .crai and .bai are generated, although most of the other tools will only use .crai index. .bai index may 
contain some useful information that can be used by Sentieon and other tools`. 
```
Additionally reading the BAM spec shows:
```
BAM indexes are supported by using 4-byte integer pointers called landmarks that are stored in container
header. BAM index pointer is a 64-bit value with 48 bits reserved for the BAM block start position and 16 bits
reserved for the in-block offset. When used to index CRAM files, the first 48 bits are used to store the CRAM
container start position and the last 16 bits are used to store the index of the landmark in the landmark array …
```
=> 🐛  drop cram bai

readme.md, subworkflows/bwa_payload_to_realn_bam.cwl, subworkflows/kfdrc_process_bam.cwl, subworkflows/kfdrc_process_bamlist.cwl, subworkflows/kfdrc_process_pe_readslist2.cwl, subworkflows/kfdrc_process_pe_set.cwl, subworkflows/kfdrc_process_se_readslist2.cwl, subworkflows/kfdrc_process_se_set.cwl, subworkflows/kfdrc_rgbam_to_realnbam.cwl, tools/cutadapt.cwl, workflows/kfdrc_alignment_wf.cwl, workflows/kfdrc_sentieon_alignment_wf.cwl
Adds Cutadapt to the BWA/GATK and Sentieon alignment workflows.
Breakdown:
- Add tool to perform cutadapt in various cases
- Add conditional cutadapt step to `subworkflows/bwa_payload_to_realn_bam.cwl`; complicated conditional to only run in the correct instances (r1 adapter for SE fastq and bam; r1+r2 adapters for PE fastq and bam)
- Adjust the bwa mem step of `subworkflows/bwa_payload_to_realn_bam.cwl` for new conditional source of files
- Add conditional cutadapt step to `subworkflows/kfdrc_process_pe_set.cwl`, `subworkflows/kfdrc_process_se_set.cwl`, and `subworkflows/kfdrc_rgbam_to_realnbam.cwl`; simpler conditionals for more constrained cases
- Add new expressionTool to `subworkflows/kfdrc_rgbam_to_realnbam.cwl` to circumvent a CAVATICA bug; CAVATICA was not performing `pickValue` …
=> ✂️  add cutadapt

subworkflows/bwa_payload_to_realn_bam.cwl, tools/samtools_split.cwl, tools/sentieon_collectvcmetrics.cwl, tools/sentieon_haplotyper.cwl, workflows/kfdrc_sentieon_alignment_wf.cwl
Some bug fixes and cleanup work resulting from our work with HudsonAlpha:
- Set the chunksize for BWA to match what we are doing in our alignment workflow
- Adjusted the samtools split output naming so it could survive read group names with `/` in them (samtools will treat those as part of an absolute path)
- Added more explicit secondaryFiles for Haplotyper and CollectVCMetrics
- Removed unnecessary bam merging step. Most Sentieon tools can merge on input, including markdups
Closes https://github.com/d3b-center/bixu-tracker/issues/2208
* Environment:
* …
=> 🐛  sentieon alignment cleanup

scripts/create_sequence_groups.py, subworkflows/kfdrc_rgbam_to_realnbam.cwl, tools/picard_collectgcbiasmetrics_conditional.cwl, tools/picard_qualityscoredistribution_conditional.cwl, tools/python_createsequencegroups.cwl, tools/samtools_idxstats_xy_ratio.cwl, workflows/kfdrc_alignment_wf.cwl
This PR is a series of changes I made to the alignment workflow so that it could be run in a cwltool runner environment.
- Add missing requirements for rgbam subworkflow and python tool
- In rgbam workflow, I needed to adjust the input selection for the array picking tool. Basically, for conditional steps that are scattered, Cavativa/Bunny will represent an skipped scatter step as `null`; cwltool on the other hand will represent it as `[null, null, null, ...]`. I wrote an expression that handles both in a faux-first_non_null fashion
- Fixed a broken glob in a picard metrics tool
- For the createsequencegroups tool, I moved the python script from the command line to a file. We could probably go further and move this into the scripts dir. Either way, the old way of doing things was causing …
=> 🐛 alignment workflow cwltool compatibility

workflows/kfdrc_alignment_wf.cwl, workflows/kfdrc_sentieon_alignment_wf.cwl
Fixes the optional scattering functionality of knownsite indexing
Closes https://github.com/d3b-center/bixu-tracker/issues/2293
Sentieon
BWA/GATK
* Environment:
* Test files:
=> 🐛  enforce array length

subworkflows/bwa_payload_to_realn_bam.cwl, subworkflows/rgbam_to_bwa_payload.cwl, tools/biobambam_bamtofastq.cwl, tools/sentieon_bwa_sort.cwl, workflows/kfdrc_sentieon_alignment_wf.cwl
BixOps reported two issues:
- Sentieon BWA was running out of memory on a very large input
- Heavily stacked bamtofastq jobs were using up all available disk space (1 TB) on the stacked VM
As a result, I've opened the CPU and RAM ports for the following steps:
- bamtofastq: If a job is running out of disk space, OPs can increase the CPU and/or RAM request for this job to reduce the number of concurrent scatters. Previously, jobs were only requesting 1 GB of RAM; therefore, they were able to stack up to 72 times on a c5.9xlarge instance. I've adjusted the default to be 1 CPU and 2GB RAM. Additionally, I changed the stacking instance to `c5.xlarge` (4 CPUs/8 GB RAM). As a result, stacking is limited to a max of 4. With the concurrent instances currently at 4, this means we will be able to …
=> 🐎  open bam processing resource ins

tools/t1k.cwl, workflows/kfdrc_alignment_wf.cwl, workflows/kfdrc_sentieon_alignment_wf.cwl
T1k was failing for some samples due to running out of RAM. This PR:
- Ups the default RAM to 32 since the failure rate due to RAM was about 50% at 16 (for WGS).
- Opens the RAM port to OPs should they need to adjust it beyond 32.
* Environment:
* Test files:
=> 🧠  adjust t1k memory

docs/KFDRC_SENTIEON_ALIGNMENT_GVCF_WORKFLOW_README.md, tools/sentieon_ReadWriter.cwl, tools/sentieon_dedup.cwl, workflows/kfdrc_sentieon_alignment_wf.cwl
Adds a memory hook for Sentieon Dedup. The tool has been shown to be memory hungry.
Fixes # (issue)
* Environment:
* Test files:
=> :brain: memory hook for dedup

docs/KFDRC_BWA_GATK_ALIGNMENT_GVCF_WORKFLOW_README.md, docs/dockers_bwagatk_alignment.md, tools/bwa_mem_naive.cwl, tools/sambamba_merge_anylist.cwl, workflows/kfdrc_alignment_wf.cwl
While working on the Nextflow port, I discovered an inefficiency in the BWA GATK pipeline. Currently we do:
- For each Read Group (shard): bwa mem | samblaster | sambamba sam to bam | sambamba natural sort
- sambamba merge all shards
- sambamba coordinate sort
The problem with this approach is that doing `natural sort -> merge -> coordinate sort` is unnecessary. Merge just needs files that are all sorted in _any_ way (natural, lex, coordinate) and it returns a file with the same sorting order as the input. In other words, if we give it coordinate sorted BAMs it will return a coordinate sorted BAM.
So if we change the bwa pipe to coordinate sort instead of natural sort that means we would not need to perform the coordinate sort post merge. This optimization would save us roughly an hour on …
=> 🐎  move sort to bwa pipe

tools/bwa_mem_naive.cwl, tools/sambamba_merge_anylist.cwl
Fixes an issue where BAMs would lose their BAI index when we "skip" merging.
Fixes https://d3b.atlassian.net/browse/BIXU-4016
* Environment:
* Test files:
=> 🐛  fix bam index capture
